### ISSUE TITLE
exe file didn't open at all

### ISSUE THREAD

**Issue by nrahman69** [KuhakuPixel/AjaxChessBot#2]
exe file didn't open at all

**Comment by KuhakuPixel** [comment]
> exe file didn't open at all

Can you send a video of you opening the exe?  so that I can get a better look on the problem and possible solutions

**Comment by Alkerstar** [comment]
¿Hay alguna solución para el problema de que el archivo exe no se abre?

**Comment by KuhakuPixel** [comment]
duplicate from
https://github.com/KuhakuPixel/AjaxChessBot/issues/3
