### ISSUE TITLE
Importing chess engine fail

### ISSUE THREAD

**Issue by urmumsas** [KuhakuPixel/AjaxChessBot#7]
I am trying to import Stockfish 15.1 into the Ajax Chess bot. Each time that I do it, it shows an error and then closes. I am not sure what is happening, and I am PRETTY SURE that it is UCI compatible. However, I do not know how to check.

**Comment by KuhakuPixel** [comment]
can you try to run the exe program in the  terminal? 

it should gives more error message if there is an error rather than double clicking the exe

**Comment by urmumsas** [comment]
The chess bot or stockfish?

**Comment by urmumsas** [comment]
Also can you tell me how?

**Comment by KuhakuPixel** [comment]
I mean the chessbot, to run exe in terminal, read this guide 

https://superuser.com/questions/494538/how-do-i-open-a-program-via-the-command-prompt-in-windows-8

**Comment by urmumsas** [comment]
Still doesn't work when I run the exe through cmd line and then import. Idk if this is helpful, but I am using a popcnt stockfish 15

**Comment by KuhakuPixel** [comment]
can you run the initial exe program succsessfully in the terminal (without the import part) ? 

if yes then give me a screenshot of the terminal
I want to see the output

**Comment by urmumsas** [comment]
![image](https://user-images.githubusercontent.com/83561104/222877090-3042ebf7-1201-48ca-9ac6-22229f27b083.png)

**Comment by KuhakuPixel** [comment]
thanks, then can take screenshot after you use `import` command

**Comment by urmumsas** [comment]
![image](https://user-images.githubusercontent.com/83561104/222878682-ecd71977-7498-42f1-98a1-e70117f54755.png)

**Comment by KuhakuPixel** [comment]
try to run as admin,

**Comment by urmumsas** [comment]
Doesn't work when importing still.

**Comment by KuhakuPixel** [comment]
It seems your input path is wrong

`C:\Users\datwo\Downloads\stockfish_15.1_win_x64_popcnt\stockfish_15.1_win_x64_popcnt`
you should add `.exe` at the end 
`C:\Users\datwo\Downloads\stockfish_15.1_win_x64_popcnt\stockfish_15.1_win_x64_popcnt.exe`

read [here](https://stackoverflow.com/a/35032054/14073678) for more details

**Comment by urmumsas** [comment]
Actually, I tried something else and it worked 
![image](https://user-images.githubusercontent.com/83561104/223308116-7134745e-b745-4b46-bcb3-45f6b7056d9d.png)

**Comment by KuhakuPixel** [comment]
okay, I guess issue is solved?
